name: dsn-hackathon-2026
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.1.4
  - scikit-learn=1.4.2
  - catboost=1.2.10
  - scipy=1.12.0
  - pip:
    - lightgbm==4.6.0
    - xgboost==3.2.0
